# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FuncationInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FuncationForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(20, 10, 521, 421))
        self.treeWidget.setMinimumSize(QtCore.QSize(521, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(521, 16777215))
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setMidLineWidth(0)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(True)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        self.treeWidget.headerItem().setFont(1, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(250)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(18)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(614, 403, 111, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(610, 50, 112, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "指标名称"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "权重"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "藏香标准实施综合评价"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "标准实施保障"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "标准发布"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("Form", "推广形式"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("Form", "标准获取时间"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("Form", "标准宣惯"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("Form", "标准问题反馈"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("Form", "政策引导"))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(0, _translate("Form", "标准质量"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "标准实施过程"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("Form", "生产制造企业"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("Form", "检测机构"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("Form", "销售企业"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("Form", "消费者"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "标准实施效果"))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("Form", "质量状况"))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("Form", "社会效益"))
        self.treeWidget.topLevelItem(0).child(2).child(2).setText(0, _translate("Form", "经济效益"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("Form", "计算权重"))
        self.pushButton.setText(_translate("Form", "专家评价"))
        self.pushButton_2.setText(_translate("Form", "计算结果"))
        self.pushButton_3.setText(_translate("Form", "退出"))
        self.pushButton_5.setText(_translate("Form", "添加节点"))
        self.pushButton_6.setText(_translate("Form", "修改节点"))
        self.pushButton_7.setText(_translate("Form", "删除节点"))

